// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEm3Ra_kZY76XENYu-MAloGhEcqXa6UvE',
    appId: '1:97319163599:web:de5a1412879f68e31c49ba',
    messagingSenderId: '97319163599',
    projectId: 'glpi-3c29f',
    authDomain: 'glpi-3c29f.firebaseapp.com',
    storageBucket: 'glpi-3c29f.firebasestorage.app',
    measurementId: 'G-FQ5GDGWX8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwocJdlQQqvQ4qP5VfyWpnLiaVHJmlE60',
    appId: '1:97319163599:android:789bee13e9bfb2dc1c49ba',
    messagingSenderId: '97319163599',
    projectId: 'glpi-3c29f',
    storageBucket: 'glpi-3c29f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-h4PT9rZ5C87-nnVH8KOqVDUQc7-dA3I',
    appId: '1:97319163599:ios:e4d9e85da23909191c49ba',
    messagingSenderId: '97319163599',
    projectId: 'glpi-3c29f',
    storageBucket: 'glpi-3c29f.firebasestorage.app',
    iosBundleId: 'com.example.glpiTechScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-h4PT9rZ5C87-nnVH8KOqVDUQc7-dA3I',
    appId: '1:97319163599:ios:e4d9e85da23909191c49ba',
    messagingSenderId: '97319163599',
    projectId: 'glpi-3c29f',
    storageBucket: 'glpi-3c29f.firebasestorage.app',
    iosBundleId: 'com.example.glpiTechScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEm3Ra_kZY76XENYu-MAloGhEcqXa6UvE',
    appId: '1:97319163599:web:43dd6e7bdf177e401c49ba',
    messagingSenderId: '97319163599',
    projectId: 'glpi-3c29f',
    authDomain: 'glpi-3c29f.firebaseapp.com',
    storageBucket: 'glpi-3c29f.firebasestorage.app',
    measurementId: 'G-8Q362T5R4F',
  );
}
